env: standard
runtime: python312

entrypoint: gunicorn -b 0.0.0.0:8080 app:server

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 5
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

resources:
    cpu: 1
    memory_gb: 1
    disk_size_gb: 1
